base_url = "https://faultypointer.github.io"

# about me
title = "Faulty's blog"
description = "The carbon and nitrogen of my life."
author = "faultypointer"

# disable sass and search index
compile_sass = false
build_search_index = false

# generate atom feed
feed_filenames = [ "atom.xml" ]
generate_feeds = true

# enable tags
taxonomies = [
    {name = "tags", output = false}
]

# enable code highlighting
[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

# extra stuff
[extra]
author = "faultypointer"
email = "faultypointer@proton.me"
profile = "/thumbnail.png"
