base_url = "https://blog.carboxi.de"

# about me
author ="(iac@scientiac.space) scientiac"
title = "carboxide"
description = "The carbons and oxygens of my life."

# disable sass and search index
compile_sass = false
build_search_index = false

# generate atom feed
feed_filenames = [ "atom.xml", "rss.xml" ]
generate_feeds = true

# enable tags
taxonomies = [
    {name = "tags", output = false}
]

# enable code highlighting
[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

# extra stuff
[extra]
email = "iac@scientiac.space"
profile = "/thumbnail.png"
note = "I am a computer engineering student who loves FOSS and is learning about privacy, the internet, and languages. I sometimes write poems, stories, and occasionally some articles too. TL;DR: I write things, test things, make things, and break things."
