base_url = "https://faulty.carboxi.de"

# about me
author ="faulty"
title = "faulty:carboxide"
description = "something something nitrogen"

# disable sass and search index
compile_sass = false
build_search_index = false

# generate atom feed
feed_filenames = [ "atom.xml", "rss.xml" ]
generate_feeds = true

# enable tags
taxonomies = [
    {name = "tags", output = false}
]

# enable code highlighting
[markdown]
highlight_code = true
highlight_theme = "nord"

# extra stuff
[extra]
url = "faulty.carboxi.de"
email = "faultypointer@proton.me"
profile = "/thumbnail.png"
note = "book"
