name: Send Webmentions
on:
  workflow_run:
    workflows: ["Zola on GitHub Pages"]
    types:
      - completed
jobs:
  send_webmentions:
    name: Send Webmentions with Delay
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Wait for Delay
        run: sleep 60  # Waits for 1 minute (60 seconds) before running the next steps
        
      - name: Read Site URL from CNAME
        id: get_url
        run: |
          SITE_URL=$(cat static/CNAME)
          echo "site_url=$SITE_URL" >> $GITHUB_OUTPUT
        
      - name: Install Webmention Package
        run: npm install @remy/webmention
        
      - name: Send Webmentions
        run: npx webmention https://${{ steps.get_url.outputs.site_url }}/atom.xml --limit=0 --send
